// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBHw1WS0bQgaowxOEM5Gjbn8lPF7Zut9ho',
    appId: '1:835360947094:web:31caceecabf12640c33bb7',
    messagingSenderId: '835360947094',
    projectId: 'pr-9-ad3bb',
    authDomain: 'pr-9-ad3bb.firebaseapp.com',
    storageBucket: 'pr-9-ad3bb.appspot.com',
    measurementId: 'G-0VQ60LKF6J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCojPyk7AvHM-TwynNUrA3Y4SoeJdgGg5g',
    appId: '1:835360947094:android:b44637eeea2650f1c33bb7',
    messagingSenderId: '835360947094',
    projectId: 'pr-9-ad3bb',
    storageBucket: 'pr-9-ad3bb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBnitHrluv5KaGawLKn3ie3WzaMntp61sY',
    appId: '1:835360947094:ios:627843f303249ac7c33bb7',
    messagingSenderId: '835360947094',
    projectId: 'pr-9-ad3bb',
    storageBucket: 'pr-9-ad3bb.appspot.com',
    iosBundleId: 'com.example.practicales',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBnitHrluv5KaGawLKn3ie3WzaMntp61sY',
    appId: '1:835360947094:ios:7cdbcd7dd8f3e391c33bb7',
    messagingSenderId: '835360947094',
    projectId: 'pr-9-ad3bb',
    storageBucket: 'pr-9-ad3bb.appspot.com',
    iosBundleId: 'com.example.practicales.RunnerTests',
  );
}
